#!/bin/bash
# create a dedicated account for hadoop
#sudo ./src/create_ubuntu

# bootstrap as ubuntu
    # generate ssh key 
    # install java
    # create directories
sudo su ubuntu -c ./src/bootstrap

# install hadoop (2.2.0)
sudo su ubuntu -c ./src/hadoop

# install scala (2.10.3)
sudo su ubuntu -c ./src/scala

# install spark (1.0)
sudo su ubuntu -c ./src/spark
sudo su ubuntu -c ./src/ipython
#sudo su ubuntu -c ./src/sparkR
