#!/bin/bash
# create a dedicated account for hadoop
sudo ./src/create_hduser

# bootstrap as hduser
    # generate ssh key 
    # install java
    # create directories
sudo su hduser -c ./src/bootstrap

# install hadoop (2.2.0)
sudo su hduser -c ./src/hadoop

# install scala (2.10.3)
sudo su hduser -c ./src/scala

# install spark (1.0)
sudo su hduser -c ./src/spark
sudo su hduser -c ./src/sparkR
