#!/bin/bash

# Generate ssh key
ssh-keygen -q -t rsa -P '' -f ~/.ssh/id_rsa
touch ~/.ssh/known_hosts
sudo chown -R hduser:hduser ~/.ssh 
sudo chown hduser:hduser ~/.ssh/known_hosts
# add ssh key to authorized_keys for localhost login
sleep 1
cat ~/.ssh/id_rsa.pub | tee ~/.ssh/authorized_keys
sleep 1
sudo cat ~ubuntu/.ssh/authorized_keys | tee -a /home/hduser/.ssh/authorized_keys

# update
sudo apt-get -qq update
sudo apt-get -y -qq upgrade
sudo apt-get install -y python-dev fabric maven
# Install java PreReq
## JAVA
command -v javac>/dev/null 2>&1 || { echo >&2 "I require java but it's not \
        installed. Installing java"; sudo apt-get install -y -qq \
        default-jdk;}
#sudo ln -s /usr/lib/jvm/java-7-openjdk-amd64 /usr/lib/jvm/default-java
# if java_home is not set
if [ -z "$JAVA_HOME" ]; then
    echo "export JAVA_HOME=/usr/lib/jvm/default-java" >> ~/.pam_environment
    source ~/.pam_environment
fi

# Create Directories

DOWNLOAD_DIR=~/Downloads
if [ ! -d $DOWNLOAD_DIR ]; then
    mkdir $DOWNLOAD_DIR
fi

INSTALL_DIR=~/DataAnalysis
if [ ! -d $INSTALL_DIR ]; then
     mkdir $INSTALL_DIR
fi


HADOOP_DIR=$INSTALL_DIR/hadoop
SCALA_DIR=$INSTALL_DIR/scala
SPARK_DIR=$INSTALL_DIR/spark


echo "export INSTALL_DIR=$INSTALL_DIR " | tee -a ~/.pam_environment
echo "export DOWNLOAD_DIR=$DOWNLOAD_DIR " | tee -a ~/.pam_environment
echo "export MAVEN_OPTS="-Xmx2g -XX:MaxPermSize=512M -XX:ReservedCodeCacheSize=512m" " | tee -a ~/.pam_environment

echo "export HADOOP_PREFIX=$HADOOP_DIR" | tee -a ~/.pam_environment
echo "export HADOOP_HOME=$INSTALL_DIR/hadoop" | tee -a ~/.pam_environment
echo "export YARN_HOME=$INSTALL_DIR/hadoop" | tee -a ~/.pam_environment

echo "export HADOOP_CONF_DIR=$INSTALL_DIR/hadoop/etc/hadoop" | tee -a ~/.pam_environment
echo "export YARN_CONF_DIR=$INSTALL_DIR/hadoop/etc/hadoop" | tee -a ~/.pam_environment
 
echo "export SCALA_HOME=$INSTALL_DIR/scala" | tee -a ~/.pam_environment
echo "export SPARK_HOME=$INSTALL_DIR/spark" | tee -a ~/.pam_environment
echo "source ~/.pam_environment" | tee -a ~/.bashrc 
