#!/bin/bash


# Create hadooop group and hduser
sudo useradd hduser -p hadoop -s /bin/bash -m
# give sudo permissions
echo 'hduser ALL=(ALL) NOPASSWD:ALL' | sudo tee /etc/sudoers.d/hduser
sudo chmod 0440 /etc/sudoers.d/hduser


