#!/bin/bash

source ~/.pam_environment

mode=$1

#check if hostname resolves
#otherwise add to hosts file
HOSTNAME=$(hostname)
IP=$(hostname -I)

echo "$IP $HOSTNAME" | sudo tee -a /etc/hosts
ssh-keyscan $HOSTNAME | sudo tee -a ~/.ssh/known_hosts
slaves=$(cat $HADOOP_CONF_DIR/slaves)

if [ $mode == "cluster" ] then 

    for slave in $slaves
    do 
        ssh-keyscan $slave | sudo tee -a ~/.ssh/known_hosts
        scp -r $HADOOP_CONF_DIR hduser@$slave:~/DataAnalysis/hadoop/etc/hadoop/
    done
fi

chown hduser:hduser /home/hduser/.ssh/known_hosts

sed -i "s/XXXX/$HOSTNAME/g" $HADOOP_CONF_DIR/core-site.xml
sed -i "s/XXXX/$HOSTNAME/g" $HADOOP_CONF_DIR/yarn-site.xml

hdfs namenode -format
start-dfs.sh
start-yarn.sh

hdfs dfs -mkdir /user
hdfs dfs -mkdir /user/hduser
