#!/bin/bash

## HADOOP
#
CONF_FILES_DIR=./src/hadoop_conf
export HADOOP_HOME=/usr/local/hadoop
source ~/.pam_environment
hadoop -h 2>&1>/dev/null
if [ $? == 0 ]; then
    echo 'Hadoop was found'
else
#    wget 
#    https://archive.apache.org/dist/hadoop/core/hadoop-2.4.0/hadoop-2.4.0.tar.gz\
    wget https://www.dropbox.com/s/4u3gkf5efpdx4op/hadoop-2.4.0.tar.gz -P $DOWNLOAD_DIR
    tar -xzf $DOWNLOAD_DIR/hadoop-2.4.0.tar.gz -C $DOWNLOAD_DIR
    sudo mv $DOWNLOAD_DIR/hadoop-2.4.0 $HADOOP_HOME
    sudo chown -R $USER $HADOOP_HOME

    #create directory for hadoop to store files
    mkdir -p /home/$USER/data

    CONF_FILES_DIR=./src/hadoop_conf

    # copy configuration files for hadoop
    cp $CONF_FILES_DIR/core-site.xml $HADOOP_CONF_DIR/
    cp $CONF_FILES_DIR/mapred-site.xml $HADOOP_CONF_DIR/
    cp $CONF_FILES_DIR/hdfs-site.xml $HADOOP_CONF_DIR/
    cp $CONF_FILES_DIR/yarn-site.xml $HADOOP_CONF_DIR/
    cp $CONF_FILES_DIR/yarn-site.xml.slave $HADOOP_CONF_DIR/
    
    chmod -R 755 $HADOOP_HOME
    echo "export PATH=$PATH:$HADOOP_PREFIX/bin:$HADOOP_PREFIX/sbin" | tee -a ~/.pam_environment
    echo "export JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk.x86_64/jre" | tee -a \
    $HADOOP_CONF_DIR/yarn-env.sh

    echo "export JAVA_HOME=/usr/lib/jvm/java-1.7.0-openjdk.x86_64/jre" | tee -a \
    $HADOOP_CONF_DIR/hadoop-env.sh

    echo "export HADOOP_NAMENODE_USER=$USER" | tee -a \
    $HADOOP_CONF_DIR/hadoop-env.sh

    echo "export HADOOP_DATANODE_USER=$USER" | tee -a \
    $HADOOP_CONF_DIR/hadoop-env.sh

    echo "export HADOOP_SECONDARYNAMENODE_USER=$USER" | tee -a \
    $HADOOP_CONF_DIR/hadoop-env.sh

    echo "export HADOOP_JOBTRACKER_USER=$USER" | tee -a \
    $HADOOP_CONF_DIR/hadoop-env.sh
    
    echo "export HADOOP_TASKTRACKER_USER=$USER" | tee -a \
    $HADOOP_CONF_DIR/hadoop-env.sh


    echo "***** HADOOP DONE! *****"

fi
