#!/bin/bash

## HADOOP
#
pwd=$PWD
source ~/.pam_environment
export SCALA_HOME=/usr/local/scala

## SCALA
scalac -help 2>&1>/dev/null
if [ $? == 0  ]; then
    echo 'Scala was found'
else
    # download the src for hadoop, scala and spark
    wget http://scala-lang.org/files/archive/scala-2.10.4.tgz -P $DOWNLOAD_DIR
    #Extract hadoop and Scala
    tar -zxf $DOWNLOAD_DIR/scala-2.10.4.tgz -C $DOWNLOAD_DIR
    sudo mv $DOWNLOAD_DIR/scala-2.10.4 $SCALA_HOME
    sudo chown -R hduser:hduser $SCALA_HOME
    chmod -R 755 $SCALA_HOME
    echo "***** Now Copying Scala *****"
    echo "export PATH=$PATH:$SCALA_HOME/bin" | tee -a ~/.pam_environment
fi

