#!/bin/bash

export CONF_FILES_DIR=./src/hadoop_conf
export SPARK_CONF_DIR=/usr/local/spark/conf
source ~/.pam_environment
wget http://d3kbcqa49mib13.cloudfront.net/spark-1.3.0-bin-hadoop2.4.tgz -P $DOWNLOAD_DIR
tar -xzf $DOWNLOAD_DIR/spark-1.3.0-bin-hadoop2.4.tgz -C $DOWNLOAD_DIR
sudo mv $DOWNLOAD_DIR/spark-1.3.0-bin-hadoop2.4 $SPARK_HOME
sudo chown -R hduser:hduser $SPARK_HOME
cp $CONF_FILES_DIR/spark-env.sh $SPARK_CONF_DIR/

cd $SPARK_HOME
cp conf/log4j.properties.template conf/log4j.properties
cp $HADOOP_CONF_DIR/slaves $SPARK_HOME/conf/
echo "export PATH=$PATH:$SPARK_HOME/bin" | tee -a ~/.pam_environment
echo "export PATH=$PATH:$SPARK_HOME/sbin" | tee -a ~/.pam_environment
echo "*********** Spark Done ************"

