#!/bin/bash

CONF_FILES_DIR=./src/config_files
export SPARK_CONF_DIR=/usr/local/spark/conf
export SPARK_HOME=/usr/local/spark

source ~/.pam_environment
wget http://d3kbcqa49mib13.cloudfront.net/spark-1.3.0-bin-hadoop2.4.tgz -P $DOWNLOAD_DIR
tar -xzf $DOWNLOAD_DIR/spark-1.3.0-bin-hadoop2.4.tgz -C $DOWNLOAD_DIR
sudo mv $DOWNLOAD_DIR/spark-1.3.0-bin-hadoop2.4 $SPARK_HOME
sudo chown -R ubuntu:ubuntu $SPARK_HOME
cp $CONF_FILES_DIR/spark-env.sh $SPARK_CONF_DIR/
cp $CONF_FILES_DIR/spark-defaults.conf $SPARK_CONF_DIR/

cd $SPARK_CONF_DIR
cp log4j.properties.template log4j.properties

echo 'MASTER=spark://$(hostname):7077' | tee -a ~/.pam_environment
echo "export PATH=$PATH:$SPARK_HOME/bin:$SPARK_HOME/sbin" | tee -a ~/.pam_environment
echo "*********** Spark Done ************"

